<?php

namespace ContainerB1hxOXZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_JsonStreamer_CacheWarmer_StreamerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.json_streamer.cache_warmer.streamer' shared service.
     *
     * @return \Symfony\Component\JsonStreamer\CacheWarmer\StreamerCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'StreamerCacheWarmer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'Mapping'.\DIRECTORY_SEPARATOR.'PropertyMetadataLoaderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'Mapping'.\DIRECTORY_SEPARATOR.'Write'.\DIRECTORY_SEPARATOR.'AttributePropertyMetadataLoader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'Mapping'.\DIRECTORY_SEPARATOR.'Write'.\DIRECTORY_SEPARATOR.'DateTimeTypePropertyMetadataLoader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'Mapping'.\DIRECTORY_SEPARATOR.'GenericTypePropertyMetadataLoader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'Mapping'.\DIRECTORY_SEPARATOR.'PropertyMetadataLoader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'type-info'.\DIRECTORY_SEPARATOR.'TypeResolver'.\DIRECTORY_SEPARATOR.'TypeResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'type-info'.\DIRECTORY_SEPARATOR.'TypeResolver'.\DIRECTORY_SEPARATOR.'TypeResolver.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'Mapping'.\DIRECTORY_SEPARATOR.'Read'.\DIRECTORY_SEPARATOR.'AttributePropertyMetadataLoader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'Mapping'.\DIRECTORY_SEPARATOR.'Read'.\DIRECTORY_SEPARATOR.'DateTimeTypePropertyMetadataLoader.php';

        $a = new \Symfony\Component\TypeInfo\TypeResolver\TypeResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'string' => ['privates', 'type_info.resolver.string', 'getTypeInfo_Resolver_StringService', true],
            'ReflectionParameter' => ['privates', 'type_info.resolver.reflection_parameter.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionParameter_PhpdocAwareService', true],
            'ReflectionProperty' => ['privates', 'type_info.resolver.reflection_property.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionProperty_PhpdocAwareService', true],
            'ReflectionFunctionAbstract' => ['privates', 'type_info.resolver.reflection_return.phpdoc_aware', 'getTypeInfo_Resolver_ReflectionReturn_PhpdocAwareService', true],
            'ReflectionType' => ['privates', 'type_info.resolver.reflection_type', 'getTypeInfo_Resolver_ReflectionTypeService', true],
        ], [
            'string' => '?',
            'ReflectionParameter' => '?',
            'ReflectionProperty' => '?',
            'ReflectionFunctionAbstract' => '?',
            'ReflectionType' => '?',
        ]));
        $b = ($container->privates['type_info.type_context_factory'] ?? $container->load('getTypeInfo_TypeContextFactoryService'));
        $c = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'json_streamer.value_transformer.date_time_to_string' => ['privates', 'json_streamer.value_transformer.date_time_to_string', 'getJsonStreamer_ValueTransformer_DateTimeToStringService', true],
            'json_streamer.value_transformer.string_to_date_time' => ['privates', 'json_streamer.value_transformer.string_to_date_time', 'getJsonStreamer_ValueTransformer_StringToDateTimeService', true],
        ], [
            'json_streamer.value_transformer.date_time_to_string' => 'Symfony\\Component\\JsonStreamer\\ValueTransformer\\DateTimeToStringValueTransformer',
            'json_streamer.value_transformer.string_to_date_time' => 'Symfony\\Component\\JsonStreamer\\ValueTransformer\\StringToDateTimeValueTransformer',
        ]);

        return $container->privates['.json_streamer.cache_warmer.streamer'] = new \Symfony\Component\JsonStreamer\CacheWarmer\StreamerCacheWarmer([], new \Symfony\Component\JsonStreamer\Mapping\Write\AttributePropertyMetadataLoader(new \Symfony\Component\JsonStreamer\Mapping\Write\DateTimeTypePropertyMetadataLoader(new \Symfony\Component\JsonStreamer\Mapping\GenericTypePropertyMetadataLoader(new \Symfony\Component\JsonStreamer\Mapping\PropertyMetadataLoader($a), $b)), $c, $a), new \Symfony\Component\JsonStreamer\Mapping\Read\AttributePropertyMetadataLoader(new \Symfony\Component\JsonStreamer\Mapping\Read\DateTimeTypePropertyMetadataLoader(new \Symfony\Component\JsonStreamer\Mapping\GenericTypePropertyMetadataLoader(new \Symfony\Component\JsonStreamer\Mapping\PropertyMetadataLoader($a), $b)), $c, $a), ($container->targetDir.''.'/json_streamer/stream_writer'), ($container->targetDir.''.'/json_streamer/stream_reader'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
