<?php

namespace ContainerB1hxOXZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonStreamer_ValueTransformer_StringToDateTimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'json_streamer.value_transformer.string_to_date_time' shared service.
     *
     * @return \Symfony\Component\JsonStreamer\ValueTransformer\StringToDateTimeValueTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'ValueTransformer'.\DIRECTORY_SEPARATOR.'ValueTransformerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'json-streamer'.\DIRECTORY_SEPARATOR.'ValueTransformer'.\DIRECTORY_SEPARATOR.'StringToDateTimeValueTransformer.php';

        return $container->privates['json_streamer.value_transformer.string_to_date_time'] = new \Symfony\Component\JsonStreamer\ValueTransformer\StringToDateTimeValueTransformer();
    }
}
