<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAyds7cv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAyds7cv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAyds7cv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAyds7cv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAyds7cv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ayds7cv',
    'container.build_id' => '99fe747a',
    'container.build_time' => 1764187654,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAyds7cv');
