<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSfYKPme\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSfYKPme/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSfYKPme.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSfYKPme\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSfYKPme\App_KernelDevDebugContainer([
    'container.build_hash' => 'SfYKPme',
    'container.build_id' => '683c72f4',
    'container.build_time' => 1764251155,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSfYKPme');
