<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYLAzyl3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYLAzyl3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYLAzyl3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYLAzyl3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYLAzyl3\App_KernelDevDebugContainer([
    'container.build_hash' => 'YLAzyl3',
    'container.build_id' => '2a1e568d',
    'container.build_time' => 1764329359,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYLAzyl3');
